export type Job = {
  _id: string;
  title: string;
  location: string;
  salary?: string;
  salaryMin?: number;
  salaryMax?: number;
  salaryText?: string;
  company: string;
  urgent: boolean;
  fullTime?: boolean;
  featured?: boolean;
  description?: string;
  category?: string;
  contactEmail?: string;
  contactPhone?: string;
  duration?: {
    type: string;
    amount?: number;
    unit?: string;
  };
  status?: "active" | "rejected" | "scheduled" | "expired" | "closed" | "pending-verification";
  plan?: "free" | "featured" | "urgent";
  isPaid?: boolean;
  emailVerified?: boolean;
  moderationNotes?: string;
  publishAt?: string;
  featuredUntil?: string;
  expiresAt?: string;
  manageToken?: string;
  applicantCount?: number;
  views?: number;
  responseRate?: number;
  salaryVerified?: boolean;
  expirationNotified?: boolean;
  createdAt?: string;
  audit?: {
    creatorIP?: string;
    userAgent?: string;
    createdAt?: string;
  };
};
