export type Job = {
  _id: string;
  title: string;
  location: string;
  salary?: string;
  company: string;
  urgent: boolean;
  fullTime?: boolean;
  description?: string;
  contactEmail?: string;
  contactPhone?: string;
  responseRate?: number;
  salaryVerified?: boolean;
  views?: number;
  createdAt?: string;
  status?: "active" | "rejected" | "scheduled" | "expired" | "closed" | "pending-verification";
  plan?: "free" | "featured" | "urgent";
  featuredUntil?: string;
  publishAt?: string;
  expiresAt?: string;
  manageToken?: string;
};
